[[headers]]
	# Define which paths this specific [[headers]] block will cover.
	for = "/"

	[headers.values]

		Access-Control-Allow-Origin = "*"

		# X-XSS-Protection = "1; mode=block"
		# Content-Security-Policy = "frame-ancestors"

		# Multi-key header rules are expressed with multi-line strings.
		# cache-control = '''
		# max-age=0,
		# no-cache,
		# no-store,
		# must-revalidate'''
